google:
  client-id: "638590374988-00j27fgspf85dgtbau9i1c5svh8ciutu.apps.googleusercontent.com"
  client-secret: "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"
  redirect-uri: "http://localhost:8080/user/google"

naver:
  client-id: "Qus9K_Ha8Jkwvf5bdI_n"
  client-secret: "T4LBmHLPwo"
  redirect-uri: "http://localhost:8080/user/naver"

kakao:
  client-id: "74ae415425bf1b53dc8f8dcf38efc2d4"
  redirect-uri: "http://localhost:8080/user/kakao"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carblre?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asd123

  mail:
    host: smtp.gmail.com
    port: 587
    username: qkrakdth@gmail.com
    password: ilfq vyie sdrz kcxz
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000 # Socket Read Timeout (5)
          starttls:
            enable: true # StartTLS
  sms:
    api:
      key: NCSOBIHPY5PGC43T
      secret: 0YPI29KTFNORDHMB6Y7UH4SUFOS41FB5
      number: 01074418574

openai:
  api:
    key: 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