server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080
  error:
    whitelabel:
      enabled: true # ? ??? ?? ??? ??

spring:
  profiles:
    default: secure
  thymeleaf:
    enabled: false
  mvc:
    contentnegotiation:
      media-types:
        mp4: video/mp4
    view:
      prefix: /WEB-INF/view/ #JSP??? ??? ???? ???? ?????.
      suffix: .jsp #? ??? ???? ??? ?? ???? ?????.
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB #?? ?? ??? 20MB
      max-request-size: 20MB #???? ?? ?? ?? 20MB??
  devtools:
    livereload:
      enabled: true



  h2:
    console:
      enabled: true

  output:
    ansi:
      enabled: always #?? ??? ANSI ?? ??? ??? ? ??? ??

#mybatis ??
mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml  #MyBatis ?? ?? ??? ?????. **? ?? ????, *.xml ? ?? XML ??? ?????.
  configuration:
    map-underscore-to-camel-case: true #??????? ????? ???(column_name)? ?? ???(columnName)? ?? ?????.
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #SQL ?? ???? ?????.

logging:
  level:
    org.apache.ibatis: DEBUG #MyBatis ?? ??? DEBUG? ???? ???? SQL ??? ?? ?? ??? ??? ?????.

payment:
  toss:
    test_client_api_key : test_ck_4yKeq5bgrpz5kx50PN943GX0lzW6
    test_secrete_api_key : test_sk_Gv6LjeKD8aPB12aJqQeerwYxAdXy
    success_url : "http://localhost:8080/api/v1/payments/toss/success"
    fail_url : "http://localhost:8080/api/v1/payments/toss/fail"
file:
  upload-dir: C:\Users\KDP\git\Carblre\src\main\resources\static\uploardVidio
